apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodeapp
  namespace: karthik-jk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/karthik_jk/nodeapp@sha256:9c0b86b1f5b44b3c362d67158549fdab4dc9f908a8d9a8bb2a5e63c7f6869e97
        name: container-image
        resources: {}
status: {}
